name: Build and Push Docker Image

on: 
    push: 
        branches: [ feature/* ]
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs: 
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write


        steps:
        - name: Checkout code
          uses: actions/checkout@v2 #checkout my code to runner

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract Metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v3
          with:
            images: |
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

        - name: Build and Push Docker Image
          uses: docker/build-push-action@v2
          with: 
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}